// Importing the stylesheet through the module graph lets Vite hot-swap CSS (HMR)
// and bundle/minify it for production.
import "../styles.css";

// GLOBAL STATE IN state.ts

import { state, isViewName, type ViewName } from "./state.ts";

import { getElement } from "./dom.ts";

import { navigateTo } from "./utils.ts";

import { loadAllData } from "./data.ts";

import { loadBookmarksFromStorage, loadNotesFromStorage } from "./storage.ts";

import { setupEventListeners } from "./events.ts";

import {
  renderDashboard,
  populateAllDropdowns,
  renderEvidenceList,
  applyStoredBookmarkFlags,
  handleSortChange,
  clearFilters,
  handleSearchInput,
  closeEvidenceDetail,
  saveCurrentNote,
  switchPeopleTab,
  renderPeople,
  renderLocations,
  renderTimeline,
  renderWorkspace,
  saveHypothesis
} from "./render.ts";

// IMPORTS THE REFACTORED CODE FROM MODULES

// ---------------------------------------------------------------------
// DATA LOADING IN data.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// GENERIC LOOKUP HELPERS IN utils.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// NAVIGATION IN utils.ts / HASH ROUTING
// ---------------------------------------------------------------------

function handleHashChange(): void {
  const requested = window.location.hash.replace("#", "");

  // indexOf() on a string list doesn't tell TypeScript that `requested` is a
  // ViewName; the isViewName() type guard does.
  const hash: ViewName = isViewName(requested) ? requested : "dashboard";

  state.currentPage = hash;

  const sections = document.querySelectorAll(".view");

  for (let i = 0; i < sections.length; i++) {
    sections[i].classList.remove("active");
  }

  getElement("view-" + hash, HTMLElement).classList.add("active");

  const navButtons = document.querySelectorAll(".nav-btn");

  for (let n = 0; n < navButtons.length; n++) {
    navButtons[n].classList.remove("active");

    if (navButtons[n].getAttribute("data-view") === hash) {
      navButtons[n].classList.add("active");
    }
  }

  if (hash === "dashboard" && !state.viewRendered.dashboard) {
    renderDashboard();
    state.viewRendered.dashboard = true;
  } else if (hash === "evidence" && !state.viewRendered.evidence) {
    renderEvidenceList();
    state.viewRendered.evidence = true;
  } else if (hash === "people" && !state.viewRendered.people) {
    renderPeople();
    renderLocations();
    state.viewRendered.people = true;
  } else if (hash === "timeline" && !state.viewRendered.timeline) {
    renderTimeline();
    state.viewRendered.timeline = true;
  } else if (hash === "workspace") {
    // workspace is cheap enough that it always re-renders
    renderWorkspace();
  }
}

// ---------------------------------------------------------------------
// DASHBOARD IN render.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// EVIDENCE CATALOGUE IN render.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// EVIDENCE DETAIL in render.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// PEOPLE & LOCATIONS in render.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// TIMELINE in render.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// WORKSPACE in render.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// LOCAL STORAGE HELPERS (bookmarks & notes) IN storage.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// EVENT LISTENER SETUP in events.ts
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// INLINE HTML HANDLER COMPATIBILITY
// ---------------------------------------------------------------------

// The onclick="…" attributes in index.html (and in HTML generated by
// render.ts) look functions up on `window`, so they must be published there.
// Declaring them on the global Window interface keeps those assignments typed.
declare global {
  interface Window {
    navigateTo: typeof navigateTo;
    switchPeopleTab: typeof switchPeopleTab;
    handleSortChange: typeof handleSortChange;
    saveHypothesis: typeof saveHypothesis;
    closeEvidenceDetail: typeof closeEvidenceDetail;
    saveCurrentNote: typeof saveCurrentNote;
    renderEvidenceList: typeof renderEvidenceList;
  }
}

window.navigateTo = navigateTo;
window.switchPeopleTab = switchPeopleTab;
window.handleSortChange = handleSortChange;
window.saveHypothesis = saveHypothesis;
window.closeEvidenceDetail = closeEvidenceDetail;
window.saveCurrentNote = saveCurrentNote;
window.renderEvidenceList = renderEvidenceList;

// ---------------------------------------------------------------------
// INIT
// ---------------------------------------------------------------------

function initApp(): void {
  loadBookmarksFromStorage();
  loadNotesFromStorage();

  setupEventListeners({
    handleSearchInput: handleSearchInput,
    renderEvidenceList: renderEvidenceList,
    clearFilters: clearFilters,
    renderTimeline: renderTimeline
  });

  loadAllData({
    renderDashboard: renderDashboard,
    populateAllDropdowns: populateAllDropdowns,
    applyStoredBookmarkFlags: applyStoredBookmarkFlags,
    renderEvidenceList: renderEvidenceList,
    renderTimeline: renderTimeline
  })
    .then(function () {
      handleHashChange();
    })
    .catch(function (err: unknown) {
      // Without this, a failed case/people/locations request was an
      // unhandled rejection and the loading spinner stayed up forever.
      console.error("Failed to load the case file", err);

      getElement("loadingText", HTMLElement).textContent =
        "The case file could not be loaded. Please reload the page.";
    });
}

window.addEventListener("DOMContentLoaded", initApp);
window.addEventListener("hashchange", handleHashChange);
